spring:
  application:
    name: service-auth

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://yjhtest1.mysql.polardb.rds.aliyuncs.com/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: yjhuser
    password: Yjh123Password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: r-2ze3vf7vdvw0ics2j9pd.redis.rds.aliyuncs.com
    port: 6379
    password: Redispassword123
    database: 1


server:
  port: 9098
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#logging.level.org.springframework.security: DEBUG

